name: Diagnose Windows SDKs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  diagnose:
    runs-on: windows-latest

    steps:
    - name: List available Windows SDK versions
      shell: cmd
      run: |
        echo "Listing contents of C:\Program Files (x86)\Windows Kits\10\Include..."
        dir "C:\Program Files (x86)\Windows Kits\10\Include"
